/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LinesRouteImport } from './routes/lines'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApplicationsFinancingUuidRouteImport } from './routes/applications.$financingUuid'
import { Route as ApiDebugSentryRouteImport } from './routes/api.debug.sentry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesRoute = LinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsFinancingUuidRoute =
  ApplicationsFinancingUuidRouteImport.update({
    id: '/applications/$financingUuid',
    path: '/applications/$financingUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugSentryRoute = ApiDebugSentryRouteImport.update({
  id: '/api/debug/sentry',
  path: '/api/debug/sentry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lines': typeof LinesRoute
  '/orders': typeof OrdersRoute
  '/people': typeof PeopleRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$financingUuid': typeof ApplicationsFinancingUuidRoute
  '/api/debug/sentry': typeof ApiDebugSentryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lines': typeof LinesRoute
  '/orders': typeof OrdersRoute
  '/people': typeof PeopleRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$financingUuid': typeof ApplicationsFinancingUuidRoute
  '/api/debug/sentry': typeof ApiDebugSentryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lines': typeof LinesRoute
  '/orders': typeof OrdersRoute
  '/people': typeof PeopleRoute
  '/api/health': typeof ApiHealthRoute
  '/applications/$financingUuid': typeof ApplicationsFinancingUuidRoute
  '/api/debug/sentry': typeof ApiDebugSentryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/lines'
    | '/orders'
    | '/people'
    | '/api/health'
    | '/applications/$financingUuid'
    | '/api/debug/sentry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/lines'
    | '/orders'
    | '/people'
    | '/api/health'
    | '/applications/$financingUuid'
    | '/api/debug/sentry'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/lines'
    | '/orders'
    | '/people'
    | '/api/health'
    | '/applications/$financingUuid'
    | '/api/debug/sentry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LinesRoute: typeof LinesRoute
  OrdersRoute: typeof OrdersRoute
  PeopleRoute: typeof PeopleRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApplicationsFinancingUuidRoute: typeof ApplicationsFinancingUuidRoute
  ApiDebugSentryRoute: typeof ApiDebugSentryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines': {
      id: '/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$financingUuid': {
      id: '/applications/$financingUuid'
      path: '/applications/$financingUuid'
      fullPath: '/applications/$financingUuid'
      preLoaderRoute: typeof ApplicationsFinancingUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/sentry': {
      id: '/api/debug/sentry'
      path: '/api/debug/sentry'
      fullPath: '/api/debug/sentry'
      preLoaderRoute: typeof ApiDebugSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LinesRoute: LinesRoute,
  OrdersRoute: OrdersRoute,
  PeopleRoute: PeopleRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApplicationsFinancingUuidRoute: ApplicationsFinancingUuidRoute,
  ApiDebugSentryRoute: ApiDebugSentryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
